spring.application.name=prueba
spring.config.import=optional:classpath:application-local.properties
server.port=9090
spring.data.mongodb.uri=mongodb://localhost:27017/fondosdb

# --- NOTIFICACIONES (Email + SMS) ---
app.notificacion.email-envios=false
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# TWILIO
twilio.account-sid=${TWILIO_ACCOUNT_SID:}
twilio.auth-token=${TWILIO_AUTH_TOKEN:}
twilio.phone-from=${TWILIO_PHONE_FROM:}
